### PR TITLE
Find by

### PR DESCRIPTION
**Pull request by pablobm**
So that I can contribute to this gem
As your friendly open source contributor
I want the specs to run

So that I can fetch records that may or may not be present
As a user
I want to find_by_id, politely returning nil when not found

### CODE REVIEW

**Comment by leemachin** [comment]
The specs will still fail with a fresh clone, because it'll use RSpec 3.0 which doesn't include `its` any more.

Options are to rewrite the specs to not use that:

```ruby
it "should have an ID of 1" do
  expect(subject.id).to eq(1)
end
```
Or to add in the gem that `its` got extracted into:  https://github.com/dnagir/its

Or to lock the version of RSpect to 2.0.whatever.

**Comment by pablobm** [comment]
@leemachin, fear not: I have locked it to RSpec ~> 2.14.0. Check out the gemspec at the end.

**Comment by leemachin** [comment]
Ah, yes! I built it on the wrong branch. :blush:

**Comment by pablobm** [comment]
Can we merge? :-) :heart:

**Comment by leemachin** [comment]
I'm happy to do it if people are okay with giving me commit access ;)

**Comment by pablobm** [comment]
It's ok. I can merge myself. Thank you!

**Pull request merged**
